plugin:
    name: 'spycetek.frontendlogger::plugin.name'
    description: 'spycetek.frontendlogger::plugin.description'
    author: 'spycetek.frontendlogger::plugin.author'
    icon: oc-icon-leaf
    homepage: ''
